name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronized, reopened, ready_for_review]

permissions:
  contents: read

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Build for std
        run: |
          cargo build
          cargo build --features=std,fugit,embedded-hal,femtos

      - name: Build for no_std
        run: |
          cargo build --no-default-features

      - name: Run tests
        run: |
          cargo test

