name: clippy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronized, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Check rustfmt and clippy
        run: |
          cargo clippy
          cargo fmt --check
