name: rustdoc
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  rustdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build rustdoc
        run: |
          RUSTDOCFLAGS="--deny=warnings --cfg=docsrs" cargo doc --all-features
